### PR TITLE
Remove hamburger menu icon and drawer menu

### PR DESCRIPTION
**Pull request by jkerr321**
The drawer menu was populated with custom links but these have all been removed with the migration to FT.com, so this menu is no longer needed

Empty drawer menu:
image

Without header hamburger menu (don't even ask about the sorry page!): 
image

### CODE REVIEW

**Comment by nickcolley** [comment]
Niceee...

`drawer.handlebars` is deleted but I don't see the reference to it in the templates removed unless the file was never used?

**Comment by nickcolley** [comment]
Wait that's why we can remove it right, cos it was removed in the migration. Neat

**Review by nickcolley — APPROVED** [review]
Nice nice nice nice thank you

**Comment by jkerr321** [comment]
You make a good point @nickcolley! Teaches me to rush in a 5pm PR 😁

**Review by nickcolley — APPROVED** [review]
Great work as usual, thank you.

**Pull request merged**
